// creating authentication actions
const wordActionTypes = {
  // add word actions
  ADDWORD_INITIATE: 'ADDWORD_INITIATE',
  ADDWORD_SUCCESS: 'ADDWORD_SUCCESS',
  ADDWORD_FAILED: 'ADDWORD_FAILED',

  // fetch words actions
  FETCHWORDS_INITIATE: 'FETCHWORDS_INITIATE',
  FETCHWORDS_SUCCESS: 'FETCHWORDS_SUCCESS',
  FETCHWORDS_FAILED: 'FETCHWORDS_FAILED',

  // fetch words by letter actions
  FETCHWORDSBYLETTER_INITIATE: 'FETCHWORDSBYLETTER_INITIATE',
  FETCHWORDSBYLETTER_SUCCESS: 'FETCHWORDSBYLETTER_SUCCESS',
  FETCHWORDSBYLETTER_FAILED: 'FETCHWORDSBYLETTER_FAILED',

}

export default wordActionTypes;   